#!/bin/bash - 
#===============================================================================
#
#          FILE: dtfw_dynamichosts.sh
# 
#         USAGE: ./dtfw_dynamichosts.sh 
# 
#   DESCRIPTION: Dumb Terminals plug-in script to help handle Dynamic DNS, to ease
#                  remote access for ever changing IP's with the firewall.
#       OPTIONS: ---
#  REQUIREMENTS: IPTables and DTfw script. 
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Mike Redd (MikereDD), mredd@0tue0.com
#  ORGANIZATION: the Spork, Inc.
#       CREATED: 04/28/2012 10:21:44 AM PDT
#      REVISION:  ---
#===============================================================================

VER="0.1b"


DYNDNSHOSTLIST="/etc/DTfw/dtfw_dynamiclists/dtfw_dynamic_hosts.lst"
DYNDNSWHITELIST="/etc/DTfw/dtfw_dynamiclists/dtfw_dynamic_whitelist.lst"

echo -e "Cleaning DynDns Whitelist"
echo "" > $DYNDNSWHITELIST

while read line
do
    echo -e "Converting Host names to IPs"
    echo -e "$(dig +short $line >> $DYNDNSWHITELIST)" ;
done < $DYNDNSHOSTLIST;

echo -e "$(sed '1d' -i $DYNDNSWHITELIST)"
echo -e "DynDns Whitelist ready"

